services:
  archlinux-builder:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./repo:/buildzone/repo
      - ./log:/buildzone/log
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: archlinux-builder
  archlinux-builder-http:
    image: python:latest
    volumes:
      - ./repo:/repo
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
    entrypoint: ["/usr/bin/python3", "-m", "http.server", "-d", "/repo/custom"]
    restart: unless-stopped
    container_name: archlinux-builder-http
