services:
  archlinux-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./repo:/buildzone/repo
    restart: unless-stopped
    container_name: archlinux-builder
  archlinux-builder-http:
    image: python:latest
    volumes:
      - ./repo:/repo
    ports:
      - "8000:8000"
    entrypoint: ["/usr/bin/python3", "-m", "http.server", "-d", "/repo/custom"]
    restart: unless-stopped
    container_name: archlinux-builder-http