name: Build linux-mainline

on:
  schedule:
    - cron:  '10 6,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git sudo pacman-contrib
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Compile
        run: |
          mv makepkg.conf /etc/makepkg.conf
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          cd kernel
          sudo -u user ./build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: kernel/packages
