name: Build mesa git

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit to build"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel git sudo pacman-contrib
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          [ -n "${{ inputs.commit}}" ] && MESA_COMMIT="#commit=${{ inputs.commit}}"
          env
          sudo -u user MESA_COMMIT=$MESA_COMMIT  env
          #sudo -u user ./build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mesa-git
          path: packages
