name: Build mesa git

on:
  schedule:
    - cron:  '20 6,18 * * *'
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit to build"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel git sudo pacman-contrib
          mv makepkg.conf /etc/makepkg.conf
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          [ -n "${{ inputs.commit}}" ] && MESA_COMMIT="#commit=${{ inputs.commit}}"
          cd mesa
          sudo -u user MESA_COMMIT=$MESA_COMMIT ./build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mesa-git
          path: mesa/packages
